version: "3.9"

services:
  backend:
    build: .
    container_name: bukcare-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: bukcare-db
    restart: always
    environment:
      POSTGRES_USER: bukcare_user
      POSTGRES_PASSWORD: bukcare_pass
      POSTGRES_DB: bukcare_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
