"""add field to doctor

Revision ID: 05d4660c7a62
Revises: b569443b14bb
Create Date: 2025-10-18 10:36:05.531290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d4660c7a62'
down_revision: Union[str, Sequence[str], None] = 'b569443b14bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('prc_license_front', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('prc_license_back', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('prc_license_selfie', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('doctors', sa.Column('specializations_json', sa.Text(), nullable=True))
    op.drop_column('doctors', 'selfie_with_prc_url')
    op.drop_column('doctors', 'prc_license_url')
    op.drop_column('doctors', 'id_back_front_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('id_back_front_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('doctors', sa.Column('prc_license_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('doctors', sa.Column('selfie_with_prc_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('doctors', 'specializations_json')
    op.drop_column('doctors', 'is_verified')
    op.drop_column('doctors', 'prc_license_selfie')
    op.drop_column('doctors', 'prc_license_back')
    op.drop_column('doctors', 'prc_license_front')
    # ### end Alembic commands ###
