"""Update

Revision ID: 164c66405ab7
Revises: 42d0500dd918
Create Date: 2025-10-18 02:24:39.831730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164c66405ab7'
down_revision: Union[str, Sequence[str], None] = '42d0500dd918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'addresses', 'cities', ['city_id'], ['city_id'])
    op.drop_column('addresses', 'zip_code')
    op.drop_column('addresses', 'province')
    op.drop_column('addresses', 'street')
    op.drop_column('addresses', 'country')
    op.drop_column('addresses', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('street', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('province', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'city_id')
    # ### end Alembic commands ###
