"""add timestamps to doctor model

Revision ID: 3cccb689a254
Revises: b29738f78462
Create Date: 2025-11-22 16:23:08.472023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cccb689a254'
down_revision: Union[str, Sequence[str], None] = 'b29738f78462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('doctors', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'updated_at')
    op.drop_column('doctors', 'created_at')
    # ### end Alembic commands ###
