"""add_bio_and_consultation_fee_to_doctors

Revision ID: 57c5044976eb
Revises: 4c0b88c439a5
Create Date: 2025-10-24 14:05:46.109697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c5044976eb'
down_revision: Union[str, Sequence[str], None] = '4c0b88c439a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_availabilities', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('doctor_availabilities', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('doctor_availabilities', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.add_column('doctor_availabilities', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('doctor_availabilities', 'day_of_week',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index(op.f('ix_doctor_availabilities_availability_id'), table_name='doctor_availabilities')
    op.create_index(op.f('ix_doctor_availabilities_id'), 'doctor_availabilities', ['id'], unique=False)
    op.drop_column('doctor_availabilities', 'availability_id')
    op.add_column('doctors', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('doctors', sa.Column('consultation_fee', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('is_accepting_patients', sa.Boolean(), nullable=True))
    op.add_column('doctors', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('doctors', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'type')
    op.drop_column('doctors', 'updated_at')
    op.drop_column('doctors', 'created_at')
    op.drop_column('doctors', 'is_accepting_patients')
    op.drop_column('doctors', 'consultation_fee')
    op.drop_column('doctors', 'bio')
    op.add_column('doctor_availabilities', sa.Column('availability_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_doctor_availabilities_id'), table_name='doctor_availabilities')
    op.create_index(op.f('ix_doctor_availabilities_availability_id'), 'doctor_availabilities', ['availability_id'], unique=False)
    op.alter_column('doctor_availabilities', 'day_of_week',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('doctor_availabilities', 'notes')
    op.drop_column('doctor_availabilities', 'is_available')
    op.drop_column('doctor_availabilities', 'date')
    op.drop_column('doctor_availabilities', 'id')
    # ### end Alembic commands ###
