"""Add Google OAuth fields

Revision ID: 76bb1cbe07ed
Revises: 4924c2a9175f
Create Date: 2025-09-30 08:12:09.683817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76bb1cbe07ed'
down_revision: Union[str, Sequence[str], None] = '4924c2a9175f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('locale', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_profile_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_profile_complete')
    op.drop_column('users', 'locale')
    op.drop_column('users', 'picture')
    # ### end Alembic commands ###
