"""Add province relationship to Doctor

Revision ID: 9340d21ea9f7
Revises: 59ff1f914260
Create Date: 2025-11-24 22:26:07.242329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9340d21ea9f7'
down_revision: Union[str, Sequence[str], None] = '59ff1f914260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
