"""Add new column

Revision ID: 9931beb82551
Revises: 02bf7b7a0ab7
Create Date: 2025-12-02 23:20:20.522822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9931beb82551'
down_revision: Union[str, Sequence[str], None] = '02bf7b7a0ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'created_at')
    op.drop_column('doctors', 'consultation_fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('consultation_fee', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('doctors', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
