"""Add cascade deletes for user and doctor

Revision ID: 9e5b610e5fad
Revises: a10ce6d7962f
Create Date: 2025-11-22 09:50:13.771808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5b610e5fad'
down_revision: Union[str, Sequence[str], None] = 'a10ce6d7962f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
