"""Remove addresses  from Doctor table

Revision ID: a425c576ce82
Revises: a26891b3c49e
Create Date: 2025-11-22 10:35:02.437908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a425c576ce82'
down_revision: Union[str, Sequence[str], None] = 'a26891b3c49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('doctors_barangay_id_fkey'), 'doctors', type_='foreignkey')
    op.drop_constraint(op.f('doctors_city_id_fkey'), 'doctors', type_='foreignkey')
    op.drop_constraint(op.f('doctors_province_id_fkey'), 'doctors', type_='foreignkey')
    op.drop_column('doctors', 'barangay_id')
    op.drop_column('doctors', 'city_id')
    op.drop_column('doctors', 'province_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('province_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('doctors', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('doctors', sa.Column('barangay_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('doctors_province_id_fkey'), 'doctors', 'provinces', ['province_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('doctors_city_id_fkey'), 'doctors', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('doctors_barangay_id_fkey'), 'doctors', 'barangays', ['barangay_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
