"""Remove zip_code from cities

Revision ID: b569443b14bb
Revises: 164c66405ab7
Create Date: 2025-10-18 10:32:22.846975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b569443b14bb'
down_revision: Union[str, Sequence[str], None] = '164c66405ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'zip_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
